#!/bin/bash

set -e

release=buster
date=$(date +%Y-%m)

lb config noauto \
	--distribution "${release}" \
	--architectures=amd64 \
	--binary-images iso-hybrid \
	--iso-volume "Debian ${release^} ZFS Test / Rescue" \
    --image-name "debian-${release}-zfs-${date}" \
 	--archive-areas "main contrib" \
 	--linux-packages "linux-image linux-headers"
	"${@}"
